'''
https://leetcode.com/problems/find-the-difference/
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

'''
from collections import defaultdict

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        letterins = defaultdict(int)
        for l in s:
            letterins[l] += 1

        for l in t:
            letterins[l] -= 1

        for k, v in letterins.items():
            if v < 0:
                return k

                



        


